const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.solid,
		C3.Behaviors.destroy,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Behaviors.Rotate,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{FONDOINICIO: 0},
	{TITULOINICIO: 0},
	{INICIO: 0},
	{NOMBREINICIO: 0},
	{Preview: 0},
	{Sample: 0},
	{Sprite: 0},
	{Sólido: 0},
	{DestruirFueraDeLaEscena: 0},
	{azul1: 0},
	{amarilla0: 0},
	{Plataforma: 0},
	{DesplazarHasta: 0},
	{perrito: 0},
	{amarilla1: 0},
	{amarilla2: 0},
	{azul2: 0},
	{Teclado: 0},
	{azul3: 0},
	{azul5: 0},
	{azul6: 0},
	{azul4: 0},
	{floorHalf_N: 0},
	{platformIndustrial_013: 0},
	{Sprite4: 0},
	{platformIndustrial_14: 0},
	{platformIndustrial_15: 0},
	{platformIndustrial_16: 0},
	{amarilla3: 0},
	{amarilla4: 0},
	{Sprite6: 0},
	{Sprite2: 0},
	{Texto: 0},
	{Texto2: 0},
	{"1falso1": 0},
	{"1verdad": 0},
	{"1falso3": 0},
	{"1falso2": 0},
	{Sprite3: 0},
	{Texto3: 0},
	{VOLVER1: 0},
	{"2FALSO1": 0},
	{"2FALSO2": 0},
	{"2FALSO3": 0},
	{"2VERDAD": 0},
	{VOLVER2: 0},
	{"3FALSO1": 0},
	{"3VERDAD": 0},
	{"3FALSO3": 0},
	{"3FALSO2": 0},
	{VOLVER3: 0},
	{"4falso1": 0},
	{"4verdad": 0},
	{"4falso2": 0},
	{"4falso3": 0},
	{VOLVER4: 0},
	{"5verdad": 0},
	{"5falso1": 0},
	{"5falso2": 0},
	{"5falso3": 0},
	{VOLVER5: 0},
	{"6falso1": 0},
	{"6verdad": 0},
	{"6falso2": 0},
	{"6falso3": 0},
	{VOLVER6: 0},
	{Sprite7: 0},
	{FondoEnMosaico: 0},
	{FondoEnMosaico2: 0},
	{FondoEnMosaico3: 0},
	{FondoEnMosaico4: 0},
	{FondoEnMosaico5: 0},
	{FondoEnMosaico6: 0},
	{FondoEnMosaico7: 0},
	{Texto4: 0},
	{Texto5: 0},
	{FondoEnMosaico8: 0},
	{Sprite5: 0},
	{Girar: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Texto6: 0}
];

self.InstanceType = {
	FONDOINICIO: class extends self.ISpriteInstance {},
	TITULOINICIO: class extends self.ITextInstance {},
	INICIO: class extends self.IButtonInstance {},
	NOMBREINICIO: class extends self.ITextInstance {},
	Preview: class extends self.ISpriteInstance {},
	Sample: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	azul1: class extends self.ISpriteInstance {},
	amarilla0: class extends self.ISpriteInstance {},
	perrito: class extends self.ISpriteInstance {},
	amarilla1: class extends self.ISpriteInstance {},
	amarilla2: class extends self.ISpriteInstance {},
	azul2: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	azul3: class extends self.ISpriteInstance {},
	azul5: class extends self.ISpriteInstance {},
	azul6: class extends self.ISpriteInstance {},
	azul4: class extends self.ISpriteInstance {},
	floorHalf_N: class extends self.ISpriteInstance {},
	platformIndustrial_013: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	platformIndustrial_14: class extends self.ISpriteInstance {},
	platformIndustrial_15: class extends self.ISpriteInstance {},
	platformIndustrial_16: class extends self.ISpriteInstance {},
	amarilla3: class extends self.ISpriteInstance {},
	amarilla4: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	_1falso1: class extends self.IButtonInstance {},
	_1verdad: class extends self.IButtonInstance {},
	_1falso3: class extends self.IButtonInstance {},
	_1falso2: class extends self.IButtonInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	VOLVER1: class extends self.IButtonInstance {},
	_2FALSO1: class extends self.IButtonInstance {},
	_2FALSO2: class extends self.IButtonInstance {},
	_2FALSO3: class extends self.IButtonInstance {},
	_2VERDAD: class extends self.IButtonInstance {},
	VOLVER2: class extends self.IButtonInstance {},
	_3FALSO1: class extends self.IButtonInstance {},
	_3VERDAD: class extends self.IButtonInstance {},
	_3FALSO3: class extends self.IButtonInstance {},
	_3FALSO2: class extends self.IButtonInstance {},
	VOLVER3: class extends self.IButtonInstance {},
	_4falso1: class extends self.IButtonInstance {},
	_4verdad: class extends self.IButtonInstance {},
	_4falso2: class extends self.IButtonInstance {},
	_4falso3: class extends self.IButtonInstance {},
	VOLVER4: class extends self.IButtonInstance {},
	_5verdad: class extends self.IButtonInstance {},
	_5falso1: class extends self.IButtonInstance {},
	_5falso2: class extends self.IButtonInstance {},
	_5falso3: class extends self.IButtonInstance {},
	VOLVER5: class extends self.IButtonInstance {},
	_6falso1: class extends self.IButtonInstance {},
	_6verdad: class extends self.IButtonInstance {},
	_6falso2: class extends self.IButtonInstance {},
	_6falso3: class extends self.IButtonInstance {},
	VOLVER6: class extends self.IButtonInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	FondoEnMosaico: class extends self.ITiledBackgroundInstance {},
	FondoEnMosaico2: class extends self.ITiledBackgroundInstance {},
	FondoEnMosaico3: class extends self.ITiledBackgroundInstance {},
	FondoEnMosaico4: class extends self.ITiledBackgroundInstance {},
	FondoEnMosaico5: class extends self.ITiledBackgroundInstance {},
	FondoEnMosaico6: class extends self.ITiledBackgroundInstance {},
	FondoEnMosaico7: class extends self.ITiledBackgroundInstance {},
	Texto4: class extends self.ITextInstance {},
	Texto5: class extends self.ITextInstance {},
	FondoEnMosaico8: class extends self.ITiledBackgroundInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Texto6: class extends self.ITextInstance {}
}